# Generated by Django 3.1.5 on 2021-02-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='NumberLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Начало пары')),
                ('time_end', models.TimeField(verbose_name='Окончание пары')),
            ],
            options={
                'verbose_name': 'Номер пары',
                'verbose_name_plural': 'Номера пар',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Расписание на день',
                'verbose_name_plural': 'Расписание на день',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('slug', models.SlugField(verbose_name='URL преподавателя')),
                ('discipline', models.ManyToManyField(to='diary.Discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('slug', models.SlugField(max_length=64, verbose_name='URL студента')),
                ('n_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.studentgroup', verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.IntegerField(verbose_name='Номер аудитории')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.discipline', verbose_name='Дисциплина')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.schedule', verbose_name='Пара')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='n_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.studentgroup', verbose_name='Номер группы'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.weekday', verbose_name='День недели'),
        ),
    ]
