# Generated by Django 3.1.5 on 2021-02-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210219_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
