# Generated by Django 3.1.5 on 2021-02-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL объявления')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, upload_to='picture_newstudent/%Y/%m/%d', verbose_name='Иллюстрация')),
                ('published_for_parents', models.BooleanField(verbose_name='Для родителей')),
                ('published_for_teacher', models.BooleanField(verbose_name='Для учителей')),
            ],
            options={
                'verbose_name': 'Объявление ',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
