# Generated by Django 3.1.5 on 2021-03-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published_at',), 'verbose_name': 'Объявление ', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RemoveField(
            model_name='schedulegroup',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL объявления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='URL студента'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL преподавателя'),
        ),
        migrations.CreateModel(
            name='TeacherDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.discipline', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.teacher', verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Оценка')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='Коментарий')),
                ('schedulelesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.schedulegroup', verbose_name='Дисциплина')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка ',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AlterField(
            model_name='schedulegroup',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.teacherdiscipline', verbose_name='Дисциплина'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='discipline',
        ),
        migrations.AddField(
            model_name='teacher',
            name='discipline',
            field=models.ManyToManyField(through='diary.TeacherDiscipline', to='diary.Discipline',
                                         verbose_name='Дисциплина'),
        ),
    ]
