# Generated by Django 3.1.5 on 2021-03-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210305_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='schedulelesson',
        ),
        migrations.AddField(
            model_name='mark',
            name='discipline',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='diary.teacherdiscipline', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
    ]
