# Generated by Django 3.1.5 on 2021-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210305_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'дисциплину', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='teacherdiscipline',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'Дисциплины учителя'},
        ),
        migrations.CreateModel(
            name='Testik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('discipline', models.ManyToManyField(to='diary.Discipline')),
            ],
        ),
    ]
