# Generated by Django 3.1.5 on 2021-03-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20210314_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.teacherdiscipline', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.student', verbose_name='Студент'),
        ),
    ]
