# Generated by Django 3.1.5 on 2021-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20210319_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picture',
        ),
        migrations.AddField(
            model_name='news',
            name='picture1',
            field=models.ImageField(blank=True, upload_to='picture_news/%Y/%m/%d-1', verbose_name='Иллюстрация 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='picture_news/%Y/%m/%d-2', verbose_name='Иллюстрация 2'),
        ),
    ]
