# Generated by Django 3.1.5 on 2021-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20210319_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
