# Generated by Django 3.1.5 on 2021-03-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20210329_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
