# Generated by Django 3.1.5 on 2021-04-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20210329_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegroup',
            name='date',
            field=models.DateField(default='1970-01-01', verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulegroup',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.numberlesson', verbose_name='Номер пары'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'discipline', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='schedulegroup',
            unique_together={('date', 'lesson', 'discipline'), ('date', 'lesson', 'n_group')},
        ),
    ]
