# Generated by Django 3.1.5 on 2021-04-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_auto_20210424_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulegroup',
            options={'verbose_name': 'элемент расписания', 'verbose_name_plural': 'Пары'},
        ),
        migrations.RemoveField(
            model_name='schedulegroup',
            name='weekday',
        ),
    ]
