# Generated by Django 3.1.5 on 2021-04-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_auto_20210424_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-schedule_lesson',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ('-schedule_lesson',), 'verbose_name': 'Оценка ', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='discipline',
        ),
        migrations.AddField(
            model_name='comment',
            name='schedule_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.schedulegroup', verbose_name='Пара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='mean_b',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='schedule_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.schedulegroup', verbose_name='Пара'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'schedule_lesson')},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='discipline',
        ),
    ]
