# Generated by Django 3.1.5 on 2021-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20210429_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
