# Generated by Django 3.1.5 on 2021-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20210522_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdiscipline',
            name='name',
            field=models.CharField(default='Bvz', max_length=200, verbose_name='Дисциплина/Преподаватель'),
        ),
    ]
