# Generated by Django 3.1.5 on 2021-05-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_teacherdiscipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdiscipline',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Дисциплина/Преподаватель'),
        ),
    ]
